console.log(Math)
console.log(Math.abs(-5))
console.log(Math.round(4.7))
console.log(Math.ceil(4.5))
console.log(Math.floor(4.5))
console.log("Mix & Max")
console.log(Math.min(4,5,2))
console.log(Math.max(41,5,2))